title: Hedgehog Tutorials
description: >- # this means to ignore newlines until "baseurl:"
  Tutorials for the Hedgehog library, designed to aid in creating task graphs 
  for algorithms to obtain performance across CPUs and multiple co-processors.
baseurl: "hedgehog-Tutorials" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_downloads: true

# Build settings
theme: minima
# plugins:
#   - jekyll-feed
